# Generated by Django 5.0.6 on 2024-08-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
