# Generated by Django 5.0.6 on 2024-07-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_middle_name_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_standing',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_term',
            field=models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall')], default='SP', max_length=2),
        ),
    ]
