# Generated by Django 5.0.6 on 2024-08-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_middle_name_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='current',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Unemployed', 'Unemployed')], max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(default='', max_length=50),
        ),
    ]
