# Generated by Django 5.0.6 on 2024-07-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='class_standing',
        ),
        migrations.AddField(
            model_name='experience',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('FULL-TIME', 'Full-time'), ('PART-TIME', 'Part-time'), ('SELF-EMPLOYED', 'Self-employed'), ('FREELANCE', 'Freelance'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship'), ('SEASONAL', 'Seasonal'), ('UNEMPLOYED', 'Unemployed')], max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_interest',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(default='', max_length=50),
        ),
    ]
