# Generated by Django 5.0.6 on 2024-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_remove_profile_class_standing_experience_alumni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=10),
        ),
    ]
