# Generated by Django 5.0.6 on 2024-07-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_alter_profile_grad_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='current',
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Full-time', 'Part-time'), ('Full-time', 'Self-employed'), ('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Unemployed', 'Unemployed')], max_length=14),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Spring'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient')], max_length=12),
        ),
    ]
