# Generated by Django 5.0.6 on 2024-07-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_experience_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Company', 'Company'), ('Project', 'Project'), ('Extra', 'Extra'), ('None', 'None')], default='None', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='extracurricular',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='experience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='experience', to='Profile.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Unemployed', 'Unemployed')], max_length=14),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='MainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('about', models.TextField(default='', max_length=200)),
                ('current_company', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.experience')),
                ('current_extra', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.extracurricular')),
                ('current_project', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.project')),
                ('current_skill', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.skill')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Profile', to='Profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='extracurricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra', to='Profile.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='Profile.organization'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='Profile.organization'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='correct end date', violation_error_message='End date should be greater than starting date'),
        ),
    ]
