# Generated by Django 5.0.6 on 2024-07-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_organization_remove_extracurricular_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainprofile',
            name='current_skill',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
