# Generated by Django 5.0.6 on 2024-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_remove_mainprofile_current_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
