# Generated by Django 5.0.6 on 2024-07-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_organization_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainprofile',
            old_name='current_extra',
            new_name='current_extracurricular',
        ),
    ]
