# Generated by Django 5.0.6 on 2024-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_rename_current_extra_mainprofile_current_extracurricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
