# Generated by Django 5.0.6 on 2024-07-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_alter_skill_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='project_skill', to='Profile.skill'),
        ),
    ]
