# Generated by Django 5.0.6 on 2024-07-24 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_alter_project_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'skill_name')},
        ),
    ]
