# Generated by Django 5.0.6 on 2024-07-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
    ]
