# Generated by Django 5.0.6 on 2024-07-25 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_alter_skill_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_standalone',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StandaloneSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
