# Generated by Django 5.0.6 on 2024-07-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_skill_is_standalone_standaloneskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_standalone',
        ),
        migrations.AddField(
            model_name='standaloneskill',
            name='is_standalone',
            field=models.BooleanField(default=True),
        ),
    ]
