# Generated by Django 5.0.6 on 2024-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0022_remove_mainprofile_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
