# Generated by Django 5.0.6 on 2024-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0024_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='network',
            field=models.CharField(choices=[('Open to Hire', 'Open to Hire'), ('Open to Internship', 'Open to Internship'), ('Open to Job', 'Open to Job'), ('Open to Connect', 'Open to Connect')], default='Open to Connect'),
        ),
    ]
