# Generated by Django 5.0.6 on 2024-08-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0026_remove_mainprofile_about_remove_mainprofile_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
