# Generated by Django 5.0.6 on 2024-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0027_alter_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
