# Generated by Django 5.0.6 on 2024-08-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0029_alter_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network',
            field=models.CharField(choices=[('Open to Hire', 'Open to Hire'), ('Seeking Internship', 'Seeking Internship'), ('Seeking Job', 'Seeking Job'), ('Open to Connect', 'Open to Connect')], default='Open to Connect'),
        ),
    ]
