# Generated by Django 5.0.6 on 2024-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0030_alter_profile_network'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='profile',
        #     name='company_url',
        #     field=models.URLField(blank=True, default='', null=True),
        # ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
