# Generated by Django 5.0.6 on 2024-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0032_alter_profile_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
