# Generated by Django 5.0.6 on 2024-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0033_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
