# Generated by Django 5.0.6 on 2024-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0033_alter_extracurricular_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network',
            field=models.CharField(choices=[('Open to Hire', 'Open to Hire'), ('Seeking Internship', 'Seeking Internship'), ('Seeking Job', 'Seeking Job'), ('Open to Connect', 'Open to Connect')], default=''),
        ),
    ]
