# Generated by Django 5.0.6 on 2024-08-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_profile_company_url_alter_profile_about'),
        ('Profile', '0034_alter_extracurricular_description_and_more'),
    ]

    operations = [
    ]
