# Generated by Django 5.0.6 on 2024-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0035_merge_20240805_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='network',
            field=models.CharField(choices=[('Open to Hire', 'Open to Hire'), ('Seeking Internship', 'Seeking Internship'), ('Seeking Job', 'Seeking Job'), ('Open to Connect', 'Open to Connect')], default='Open to Connect'),
        ),
    ]
