# Generated by Django 5.0.6 on 2024-08-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0007_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='commentlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Feed.comment'),
        ),
    ]
