# Generated by Django 5.0.6 on 2024-08-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0007_rename_like_user_post_feed_like_user_id_fbb6b9_idx_and_more'),
        ('Feed', '0008_alter_commentlike_options_commentlike_is_like_and_more'),
    ]

    operations = [
    ]
