# Generated by Django 5.0.6 on 2024-08-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0009_merge_20240806_0303'),
        ('Feed', '0010_alter_commentlike_options_remove_commentlike_date'),
    ]

    operations = [
    ]
