# Generated by Django 5.0.6 on 2024-08-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0010_alter_commentlike_options_remove_commentlike_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
