# Generated by Django 5.0.6 on 2024-08-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0011_commentlike_date'),
        ('Feed', '0011_merge_20240806_1808'),
    ]

    operations = [
    ]
