# Generated by Django 5.0.6 on 2024-08-15 00:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0012_repost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('repost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Feed.repost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'repost'], name='Feed_repost_user_id_6a8e01_idx')],
                'unique_together': {('user', 'repost')},
            },
        ),
    ]
