# Generated by Django 5.0.6 on 2024-08-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0012_merge_0011_commentlike_date_0011_merge_20240806_1808'),
        ('Feed', '0014_commentlike_date_repostcomment'),
    ]

    operations = [
    ]
