# Generated by Django 5.0.6 on 2024-08-21 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0015_merge_20240818_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repost',
            unique_together={('original_post', 'user')},
        ),
    ]
