# Generated by Django 5.0.6 on 2024-08-21 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0016_alter_repost_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repostcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='repostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
