# Generated by Django 5.0.6 on 2024-08-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0017_alter_repostcomment_options_alter_repostcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
