# Generated by Django 5.0.6 on 2024-08-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0019_auto_20240821_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
