# Generated by Django 5.0.6 on 2024-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], max_length=20)),
                ('mode', models.CharField(choices=[('In-Person', 'In-Person'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('other_requirements', models.TextField(blank=True, null=True)),
                ('us_work_authorization', models.BooleanField()),
                ('us_citizenship', models.BooleanField()),
                ('us_residency', models.BooleanField()),
                ('application_link', models.URLField()),
            ],
        ),
    ]