# Generated by Django 5.0.6 on 2024-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='application_link',
            new_name='applicationLink',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='job_description',
            new_name='jobDescription',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='job_position',
            new_name='jobID',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='other_requirements',
            new_name='otherRequirements',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='us_citizenship',
            new_name='usCitizenship',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='us_residency',
            new_name='usResidency',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='us_work_authorization',
            new_name='usWorkAuthorization',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='jobPosition',
            field=models.CharField(default='', max_length=100),
        ),
    ]