# Generated by Django 5.0.6 on 2024-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='PID',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
