# Generated by Django 5.0.6 on 2024-07-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_appuser_options_remove_appuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='grad_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='grad_year',
            field=models.IntegerField(null=True),
        ),
    ]
