# Generated by Django 5.0.6 on 2024-07-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_remove_appuser_grad_date_remove_appuser_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
