# Generated by Django 5.0.6 on 2024-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_appuser_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='grad_term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
