# Generated by Django 5.0.6 on 2024-07-12 00:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_appuser_grad_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='grad_term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='graduation_year',
            field=models.IntegerField(null=True),  # or whatever default value you intend to use
        ),
    ]
