# Generated by Django 5.0.6 on 2024-08-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_appuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_permissions',
        ),
    ]
